### ISSUE TITLE
Starting Jmeter shows exception

### ISSUE THREAD

**Issue by WillemLT** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#12]
First put the plugin jmeter-plugin-influxdb2-listener-1.1 in the C:\Program Files (x86)\Apache-jmeter-5.4.1\lib\ext.
Then after starting Jmeter (5.4.1).

The following exception is showed:
```
2021-03-27 23:04:46,187 ERROR o.a.j.r.ClassFinder: Error filtering class okhttp3.internal.tls.BasicTrustRootIndex, it will be ignored
java.lang.IncompatibleClassChangeError: class okhttp3.internal.tls.BasicTrustRootIndex can not implement okhttp3.internal.tls.TrustRootIndex, because it is not an interface (okhttp3.internal.tls.TrustRootIndex is in unnamed module of loader org.apache.jmeter.DynamicClassLoader @53d8d10a)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:512) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:420) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:414) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:413) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:100) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:86) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:404) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.lambda$findClassesInOnePath$2(ClassFinder.java:364) ~[jorphan.jar:5.4.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:555) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:362) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:213) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:182) ~[jorphan.jar:5.4.1]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:128) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:107) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:94) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:184) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.4.1]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:312) [?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1079) ~[?:?]
	at java.awt.Component.show(Component.java:1720) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1667) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1032) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1014) ~[?:?]
	at org.apache.jmeter.SplashScreen.lambda$showScreen$0(SplashScreen.java:95) ~[ApacheJMeter_core.jar:5.4.1]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

Used openjdk 16.

And in the cmd window I see:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Program%20Files%20(x86)/Apache-jmeter-5.4.1/lib/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Program%20Files%20(x86)/Apache-jmeter-5.4.1/lib/ext/jmeter-plugin-influxdb2-listener-1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

**Comment by mderevyankoaqa** [comment]
Hi @WillemLT,  not sure for 100% but it can be due to conflicts in run time.. please remove others backend listener you have and try. Please send the screen before removing to see what plugins you put.

BR,
Mike

**Comment by WillemLT** [comment]
That works :)

**Comment by mderevyankoaqa** [comment]
@WillemLT thank you for the updates, hope the project helps you to solve your routine tasks. :)

BR,
Mike
