### ISSUE TITLE
[Distributed mode] is there any specific configuration to write test result from servers?

### ISSUE THREAD

**Issue by anna-phuongnguyen** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#22]
Hi,

I ran test in distributed mode, and I saw the jmeter servers didn't write test result to InfluxDB. They sent those results back to jmeter controller, then controller inject data to InfluxDB.
Could you consider for giving an option to allow it send test log directly to InfluxDB?

Thank you.

**Comment by mderevyankoaqa** [comment]
Hi @anna-phuongnguyen, 

The plugin should work in the cluster mode. Please make sure that you have to put that plugin on each slave, master to avoid compilation errors. Please keep in mind in the cluster mode the virtual users chart will show the users per node (but not the sum).  The InfluxDB can be overloaded in cluster mode due to a lot of connections.

BR,
Mike

**Comment by anna-phuongnguyen** [comment]
Thank you for your response @mderevyankoaqa 
Yes it works in distributed mode. But there are 2 issues:
1. It doesn't work with InfluxDB connection info are retrieved from properties file. E.g.  `jmeter -n -t test.jmx -G influxdb.properties `
2. To by pass the 1st issue, we have to pass` -q influxdb.properties ` to the run command beside -G. 
`jmeter -n -t test.jmx -G influxdb.properties  -q influxdb.properties`
Metric can be written to InfluxDB, but it resulted error when we tried to run with 2 jmeter servers. It's weird.
WARN o.a.j.v.b.BackendListenerContext: Value for parameter 'influxDBPort' not an integer: 'NONE'.  Using default: '8086'.
java.lang.NumberFormatException: For input string: "NONE"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
        at

Finally, my suggestion is to allow jmeter servers to write metric directly to influxDB, instead of send it all to controller.

Thank you

**Comment by anna-phuongnguyen** [comment]
By the way, we tried to run with multiple servers, but in InfluxDB it shown only master node name.

**Comment by mderevyankoaqa** [comment]
Hi @anna-phuongnguyen,

If you are using cluster (master and slaves) is not possible to allow JMeter servers to write metric directly to influxDB, instead of sending it all to the controller. The plugin inherits the JMeter core implementation.

You need to start the test from each JMeter slave independently manually - > if you need to send metrics directly to influxDB from each slave. In this way, the master node is not using, data for the report will be stored in influxDB.

From another hand, you will not have one file with results like in cluster - just keep in mind.

BR,
Mike
