### ISSUE TITLE
java.lang.NoSuchMethodError: 'okhttp3.HttpUrl okhttp3.HttpUrl.get(java.lang.String)'

### ISSUE THREAD

**Issue by dipakkumar1225** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#28]
**JMeter**: 5.4.1
**Influxdb** : 2.0.6
**Grafana**: grafana-enterprise-8.2.3

**jmeter-plugin-influxdb2-listener-1.3-all.jar**

Getting error java.lang.NoSuchMethodError: 'okhttp3.HttpUrl okhttp3.HttpUrl.get(java.lang.String)'

2021-11-12 23:44:30,375 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2021-11-12 23:44:30,376 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2021-11-12 23:44:30,379 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient and queue capacity: 5000
2021-11-12 23:44:30,379 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: class org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
2021-11-12 23:44:30,379 INFO o.m.j.i.v.InfluxDatabaseBackendListenerClient: InfluxDBClientFactory is going to use the following properties:
2021-11-12 23:44:30,379 INFO o.m.j.i.v.InfluxDatabaseBackendListenerClient: URL --> http://localhost:8086
2021-11-12 23:44:30,379 INFO o.m.j.i.v.InfluxDatabaseBackendListenerClient: Token --> cz-LppI6w72jXre-hNilbp-xir_v219Winng0R6IMX80OGSagyCtl1Ov0nrkRF2c9KhwSj_hixGalZ_Glt2JoA==
2021-11-12 23:44:30,379 INFO o.m.j.i.v.InfluxDatabaseBackendListenerClient: Organization --> influxadmin
2021-11-12 23:44:30,380 INFO o.m.j.i.v.InfluxDatabaseBackendListenerClient: Bucket --> newJmeter
2021-11-12 23:44:30,380 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,6,main]
java.lang.NoSuchMethodError: 'okhttp3.HttpUrl okhttp3.HttpUrl.get(java.lang.String)'
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506) ~[jmeter-plugin-influxdb-listener-1.2.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.internal.AbstractInfluxDBClient.<init>(AbstractInfluxDBClient.java:96) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.internal.InfluxDBClientImpl.<init>(InfluxDBClientImpl.java:97) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:204) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:159) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at org.md.jmeter.influxdb2.visualizer.influxdb.client.InfluxDatabaseClient.setupInfluxClient(InfluxDatabaseClient.java:150) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupInfluxClient(InfluxDatabaseBackendListenerClient.java:247) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupTest(InfluxDatabaseBackendListenerClient.java:173) ~[jmeter-plugin-influxdb2-listener-1.3-all.jar:task ':jar' property 'archiveVersion']
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:325) ~[ApacheJMeter_components.jar:5.4.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) ~[ApacheJMeter_components.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:382) ~[ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Bankend Listener Settings**
![image](https://user-images.githubusercontent.com/46619348/141519331-4c25784f-1d02-4c0f-9c10-e27ed763a7ff.png)

**Comment by mderevyankoaqa** [comment]
Hi @dipakkumar1225,

This is the specific issue. Have no such issue. 
What was Java version?  Not sure maybe you have conflicts with some other libs.. And what you have  in ~apache-jmeter-5.4.1\lib\ext? Can you send me the list.

BR,
Mike

**Comment by mderevyankoaqa** [comment]
Sorry need to close since the duplicate. The same Issue is described here https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/issues/16


BR,
Mike
