### ISSUE TITLE
Exception initialising: org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient

### ISSUE THREAD

**Issue by vsyrichev** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#31]
Hi,

I tried to import jms that uses this plugin to maven project in Idea and run it there using the jmeter-maven-plugin via 'mvn verify' command.
I got the following error:
2021-12-17 01:12:19,854 ERROR o.a.j.v.b.BackendListener: StandardJMeterEngine@4aa3d36-Backend Listener	Exception initialising: org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
java.lang.ClassNotFoundException: org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.initClass(BackendListener.java:128) [ApacheJMeter_components-5.4.1.jar:5.4.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:304) [ApacheJMeter_components-5.4.1.jar:5.4.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) [ApacheJMeter_components-5.4.1.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) [ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:382) [ApacheJMeter_core-5.4.1.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-12-17 01:12:19,892 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: null and queue capacity: 5000
2021-12-17 01:12:19,893 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: null

Actually the same approach works fine for org.apache.jmeter.visualizers.backend.influxdb.InfluxdbBackendListenerClient.

Could you please help to investigate the defect?

Thanks in advance,
Vadim

**Comment by mderevyankoaqa** [comment]
Hi @vsyrichev, have no idea to say why it was happened.. 

The plugin was supposed to be used like the JMeter part.. Are you developing something and are you trying to add this plugin like the reference?    

BR,
Mike

**Comment by mderevyankoaqa** [comment]
Closed. Now the plugin is supported in the jmeter-maven plugin, since it's in maven-central. 

BR,
Mike
