### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by pbandreddy** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#46]
Hi,
I'm getting below warning when tried to use influxDB plugin.

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/apache-jmeter-5.4.3/lib/log4j-slf4j-impl-2.17.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/apache-jmeter-5.4.3/lib/ext/jmeter-plugin-influxdb2-listener-2.0-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]`

with this warning i'm unable to use influxdb plugin.

**Comment by pbandreddy** [comment]
if i ignore above mentioned warning, i'm getting below error and can't execute the test.
`ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,6,main]
java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.internal.AbstractInfluxDBClient.<init>(AbstractInfluxDBClient.java:96) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.internal.InfluxDBClientImpl.<init>(InfluxDBClientImpl.java:96) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:204) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:159) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at org.md.jmeter.influxdb2.visualizer.influxdb.client.InfluxDatabaseClient.setupInfluxClient(InfluxDatabaseClient.java:39) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupInfluxClient(InfluxDatabaseBackendListenerClient.java:233) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at org.md.jmeter.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupTest(InfluxDatabaseBackendListenerClient.java:165) ~[jmeter-plugin-influxdb2-listener-1.1.jar:task ':jar' property 'archiveVersion']
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:325) ~[ApacheJMeter_components.jar:5.4.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) ~[ApacheJMeter_components.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:382) ~[ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by mderevyankoaqa** [comment]
@pbandreddy any news?

BR,
Mike
