### ISSUE TITLE
Error filtering class org.apache.commons.compress.harmony.pack200.Segment || While launching Jmeter

### ISSUE THREAD

**Issue by SreeCoder** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#53]
Hi Team,

I built the 4.8.1 version jar file and moved to lib/ext.  However, I get the below error while launching JMeter.  Any assistance is much appreciated.

2022-06-21 09:41:03,093 ERROR o.a.j.r.ClassFinder: Error filtering class org.apache.commons.compress.harmony.pack200.Segment, it will be ignored
java.lang.IncompatibleClassChangeError: class org.apache.commons.compress.harmony.pack200.Segment can not implement org.objectweb.asm.ClassVisitor, because it is not an interface (org.objectweb.asm.ClassVisitor is in unnamed module of loader org.apache.jmeter.DynamicClassLoader @2aaf7cc2)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:555) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:100) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:86) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:404) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.lambda$findClassesInOnePath$2(ClassFinder.java:364) ~[jorphan.jar:5.4.3]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:581) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:362) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:213) ~[jorphan.jar:5.4.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:182) ~[jorphan.jar:5.4.3]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:128) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:107) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:94) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:184) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.4.3]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1070) ~[?:?]
	at java.awt.Component.show(Component.java:1716) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1663) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1031) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1005) ~[?:?]
	at org.apache.jmeter.SplashScreen.lambda$showScreen$0(SplashScreen.java:95) ~[ApacheJMeter_core.jar:5.4.3]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

**Comment by SreeCoder** [comment]
Hi @mderevyankoaqa  
I am using JMeter 4.5.3 and JDK 11 versions.  Seems I have to use JMeter 5.5 as per your comment.  Thanks for the response.

**Comment by mderevyankoaqa** [comment]
@SreeCoder, you are right you need to use the JMeter 5.5 and the latest release of the plugin.

BR,
Mike
