### ISSUE TITLE
When I use JSR223 sampler I get exception

### ISSUE THREAD

**Issue by cah-jyoti-prakash** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#7]
Seems some class/Jar conflict.

2021-03-18 00:22:38,821 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.ExceptionInInitializerError: null
	at org.codehaus.groovy.jsr223.GroovyScriptEngineFactory.getLanguageVersion(GroovyScriptEngineFactory.java:95) ~[groovy-jsr223-3.0.7.jar:3.0.7]
	at org.apache.jmeter.util.JSR223BeanInfoSupport.<clinit>(JSR223BeanInfoSupport.java:70) ~[jmeter-plugin-influxdb-listener-1.0.jar:task ':jar' property 'archiveVersion']
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]

**Comment by dsteindo** [comment]
This seems like the same issue I opened -> #6

**Comment by cah-jyoti-prakash** [comment]
Jmeter 5.4.1
openjdk version "12.0.1" 2019-04-16

**Comment by mderevyankoaqa** [comment]
@cah-jyoti-prakash, hi thank you.. it seems the compatibility issue, will take a look soon.

**Comment by mderevyankoaqa** [comment]
Please try this one https://drive.google.com/file/d/1QhSEUDrESOjzLRFPGVkN0e_Im6FkHfyU/view
the package should be compatible with 5.4.1 .. in case if it works - will make a new release. 
Thank you.

**Comment by mderevyankoaqa** [comment]
Is going to be fixed in the new release.. Already tested, see details [Redundant dependencies #6](https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/issues/6)

**Comment by mderevyankoaqa** [comment]
Fixed in [1.1 relase](https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/releases/tag/v1.1)
