### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by shifty13626** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#70]
Hi ! 
I'm tring to use this plugin but when I'm executing the test an error appear.
```
2022-10-11 14:28:15,966 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,6,main]
java.lang.NoSuchMethodError: okhttp3.logging.HttpLoggingInterceptor.redactHeader(Ljava/lang/String;)V
	at com.influxdb.client.internal.AbstractInfluxDBClient.<init>(AbstractInfluxDBClient.java:92) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at com.influxdb.client.internal.AbstractInfluxDBClient.<init>(AbstractInfluxDBClient.java:79) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at com.influxdb.client.internal.InfluxDBClientImpl.<init>(InfluxDBClientImpl.java:99) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:261) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:180) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at io.github.mderevyankoaqa.influxdb2.visualizer.influxdb.client.InfluxDatabaseClient.setupInfluxClient(InfluxDatabaseClient.java:148) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupInfluxClient(InfluxDatabaseBackendListenerClient.java:264) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupTest(InfluxDatabaseBackendListenerClient.java:185) ~[jmeter-plugins-influxdb2-listener-2.5.jar:2.5]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:325) ~[ApacheJMeter_components.jar:5.5]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) ~[ApacheJMeter_components.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:396) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]

```

I have Java version java 11.0.12 2021-07-20 LTS
and JMeter 5.5.

I don't know how to do, can you help me?

**Comment by mderevyankoaqa** [comment]
Hi @shifty13626, please try a workaround from the issue https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/issues/16

BR,
Mike
