### ISSUE TITLE
Plugin bundles groovy which causes conflicts with JMeter

### ISSUE THREAD

**Issue by vlsi** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#86]
Try adding the plugin to the recent nightly JMeter.
The plugin shades groovy 3.0.11 while JMeter ships 3.0.17.

It would probably be better to avoid shading the dependencies

**Comment by mateusgsan** [comment]
problems occurs again with Jmeter 5.6 (groovy 3.0.17 conflicts with groovy 3.0.11)

**Comment by mateusgsan** [comment]
please just change jmeter dependencies to 5.6 version and influx client to 6.9.0  in build.gradle

**Comment by alpanachaphalkar** [comment]
@mateusgsan and @mderevyankoaqa  can you please release a fixed JAR for this issue? That would be great!

**Comment by Darthops** [comment]
I'm not sure if this is related but it only appears to occur on 5.6.2 when I add in your jmeter-plugins-influxdb2-listener-2.7.jar file.

In JMeter if I right click on Test Plan > Add Listener > View Result Tree

Then I get the following error message in the log pane:

`ERROR o.a.j.v.ViewResultsFullVisualizer: Exception registering implementation: [] of interface: [interface org.apache.jmeter.visualizers.ResultRenderer], a jar is probably missing
java.util.ServiceConfigurationError: org.apache.jmeter.visualizers.ResultRenderer: Provider org.apache.jmeter.visualizers.RenderInBrowser not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at org.apache.jorphan.reflect.ClassFinder.loadServices(ClassFinder.java:115) ~[jorphan.jar:5.6.2]
	at org.apache.jmeter.util.JMeterUtils.loadServicesAndScanJars(JMeterUtils.java:345) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.createComboRender(ViewResultsFullVisualizer.java:464) ~[ApacheJMeter_components.jar:5.6.2]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.createLeftPanel(ViewResultsFullVisualizer.java:438) ~[ApacheJMeter_components.jar:5.6.2]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.init(ViewResultsFullVisualizer.java:349) ~[ApacheJMeter_components.jar:5.6.2]
	at org.apache.jmeter.visualizers.ViewResultsFullVisualizer.<init>(ViewResultsFullVisualizer.java:156) ~[ApacheJMeter_components.jar:5.6.2]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
	at org.apache.jmeter.gui.GuiPackage.getGuiFromCache(GuiPackage.java:424) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.gui.GuiPackage.createTestElement(GuiPackage.java:371) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.gui.action.AddToTree.doAction(AddToTree.java:70) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:83) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:65) ~[ApacheJMeter_core.jar:5.6.2]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:400) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
`

When I add a "View Results Tree" it works fine if the jmeter-plugins-influxdb2-listener-2.7.jar isn't present so not sure where the issue is.

**Comment by mderevyankoaqa** [comment]
@Darthops Please check the new release https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/releases/tag/v2.7

The old jar please remove.

BR,
Mike
