### ISSUE TITLE
facing error while running jmeter script on local with dashboard id ID: 13644

### ISSUE THREAD

**Issue by mihir2314** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#89]
Hi All,
I am getting an error while executing Jmeter scipt with jmeter-influxdb2-listener-plugin as follow
```
2023-09-06 11:33:26,991 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2023-09-06 11:33:26,992 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2023-09-06 11:33:26,993 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient and queue capacity: 5000
2023-09-06 11:33:26,993 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: class io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
2023-09-06 11:33:26,994 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: InfluxDBClientFactory is going to use the following properties:
2023-09-06 11:33:26,994 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: URL --> http://localhost:8086/
2023-09-06 11:33:26,994 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: Token --> sAyMZAuQ9Zl1OsLrX-tAAsX_AhUOgrH0hRsN-qJMIejFQfjdhYqTSagJbvDxK2zOkUefSc06MtEkBseAtM7d5Q==
2023-09-06 11:33:26,994 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: Organization --> learning
2023-09-06 11:33:26,994 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: Bucket --> jmeter
2023-09-06 11:33:26,995 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,6,main]
java.lang.NoSuchMethodError: okhttp3.logging.HttpLoggingInterceptor.redactHeader(Ljava/lang/String;)V
	at com.influxdb.client.internal.AbstractInfluxDBClient.<init>(AbstractInfluxDBClient.java:92) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at com.influxdb.client.internal.AbstractInfluxDBClient.<init>(AbstractInfluxDBClient.java:79) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at com.influxdb.client.internal.InfluxDBClientImpl.<init>(InfluxDBClientImpl.java:99) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:261) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:180) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at io.github.mderevyankoaqa.influxdb2.visualizer.influxdb.client.InfluxDatabaseClient.setupInfluxClient(InfluxDatabaseClient.java:148) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupInfluxClient(InfluxDatabaseBackendListenerClient.java:262) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient.setupTest(InfluxDatabaseBackendListenerClient.java:183) ~[jmeter-plugins-influxdb2-listener-2.6.jar:2.6]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:325) ~[ApacheJMeter_components.jar:5.5]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) ~[ApacheJMeter_components.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:396) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```
please help.
thank you

**Comment by mderevyankoaqa** [comment]
Hello @mihir2314,

Please try the last release 2.74 and see the compatibilities list.

BR,
Mike
