### ISSUE TITLE
Stuck excute script jmeter at step create instance of InfluxDatabaseClient

### ISSUE THREAD

**Issue by wocruise** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#98]
```
2024-01-10 10:24:06,179 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2024-01-10 10:24:06,180 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2024-01-10 10:24:06,180 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2024-01-10 10:24:06,182 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2024-01-10 10:24:06,183 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2024-01-10 10:24:06,226 INFO o.a.j.r.ClassFinder: Will scan jar D:\jmeter-app\apache-jmeter-5.6.2\apache-jmeter-5.6.2\lib\ext\jmeter-plugins-dummy-0.4.jar with filter ExtendsClassFilter [parents=[interface org.apache.jmeter.functions.Function], inner=false, contains=null, notContains=null]. Consider exposing JMeter plugins via META-INF/services, and add JMeter-Skip-Class-Scanning=true manifest attribute so JMeter can skip classfile scanning
2024-01-10 10:24:06,227 INFO o.a.j.r.ClassFinder: Will scan jar D:\jmeter-app\apache-jmeter-5.6.2\apache-jmeter-5.6.2\lib\ext\JMeter-InfluxDB-Writer-plugin-1.2.jar with filter ExtendsClassFilter [parents=[interface org.apache.jmeter.functions.Function], inner=false, contains=null, notContains=null]. Consider exposing JMeter plugins via META-INF/services, and add JMeter-Skip-Class-Scanning=true manifest attribute so JMeter can skip classfile scanning
2024-01-10 10:24:06,233 INFO o.a.j.r.ClassFinder: Will scan jar D:\jmeter-app\apache-jmeter-5.6.2\apache-jmeter-5.6.2\lib\ext\jmeter-plugins-influxdb2-listener-2.7.jar with filter ExtendsClassFilter [parents=[interface org.apache.jmeter.functions.Function], inner=false, contains=null, notContains=null]. Consider exposing JMeter plugins via META-INF/services, and add JMeter-Skip-Class-Scanning=true manifest attribute so JMeter can skip classfile scanning
2024-01-10 10:24:06,249 ERROR o.a.j.r.ClassFinder: Error filtering class okhttp3.internal.tls.BasicTrustRootIndex, it will be ignored
java.lang.IncompatibleClassChangeError: class okhttp3.internal.tls.BasicTrustRootIndex can not implement okhttp3.internal.tls.TrustRootIndex, because it is not an interface (okhttp3.internal.tls.TrustRootIndex is in unnamed module of loader org.apache.jmeter.DynamicClassLoader @eed1f14)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:514) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:422) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:416) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:415) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:468) ~[?:?]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:198) ~[jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:184) ~[jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:541) ~[jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder.lambda$findClassesInOnePath$2(ClassFinder.java:501) ~[jorphan.jar:5.6.2]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) [?:?]
	at java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:555) [?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) [?:?]
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:499) [jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:443) [jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:413) [jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:336) [jorphan.jar:5.6.2]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:315) [jorphan.jar:5.6.2]
	at org.apache.jmeter.util.JMeterUtils.findClassesThatExtend(JMeterUtils.java:402) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.util.JMeterUtils.loadServicesAndScanJars(JMeterUtils.java:349) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.engine.util.CompoundVariable.<clinit>(CompoundVariable.java:73) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.engine.util.ValueReplacer.<init>(ValueReplacer.java:43) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.engine.PreCompiler.<init>(PreCompiler.java:54) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:404) [ApacheJMeter_core.jar:5.6.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2024-01-10 10:24:06,254 INFO o.a.j.r.ClassFinder: Will scan jar D:\jmeter-app\apache-jmeter-5.6.2\apache-jmeter-5.6.2\lib\ext\jmeter-plugins-manager-1.10.jar with filter ExtendsClassFilter [parents=[interface org.apache.jmeter.functions.Function], inner=false, contains=null, notContains=null]. Consider exposing JMeter plugins via META-INF/services, and add JMeter-Skip-Class-Scanning=true manifest attribute so JMeter can skip classfile scanning
2024-01-10 10:24:06,271 INFO o.a.j.v.b.BackendListener: Jmeter load test -influxdb 2.0: Starting worker with class: class io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient and queue capacity: 5000
2024-01-10 10:24:06,272 INFO o.a.j.v.b.BackendListener: Jmeter load test -influxdb 2.0: Started  worker with class: class io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
2024-01-10 10:24:06,273 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: New instance of InfluxDatabaseClient has been created!
2024-01-10 10:24:06,274 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: InfluxDBClientFactory is going to use the following properties:
2024-01-10 10:24:06,274 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: URL --> http://localhost:8086/
2024-01-10 10:24:06,274 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: Token --> HBEP3rtC4xwwxwBe8IfuwlUqCtwhpBxyMRr06N20LM45UANV86rqv8E69GOLO6Wb01fI2zJHTxqxzBLeno2v2w==
2024-01-10 10:24:06,274 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: Organization --> admin
2024-01-10 10:24:06,275 INFO i.g.m.i.v.InfluxDatabaseBackendListenerClient: Bucket --> telegraf
````
![2024-01-10_10-31-00](https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/assets/56554467/1f81dcc7-852f-462e-822f-64511e9c3cc8)

**Comment by mderevyankoaqa** [comment]
It seems you are using the bucket with already created mapping. 

![image](https://github.com/user-attachments/assets/198e8ff4-6295-467d-84fa-6a9e5b246999)

Please create from scratch. 

BR,
Mike
